from tensorflow/tensorflow:1.7.0-gpu

RUN apt-get update; apt-get install -y git python-pip 
RUN apt-get install -y libboost-all-dev python-tk vim
WORKDIR /opt

RUN apt-get install screen -y

ADD tflow/TF.py /opt
ADD tflow/Unet3D.py /opt
ADD requirements.txt /opt

RUN pip install -r requirements.txt
